### ISSUE TITLE
GETpointsFromPolygon: Identify costs, improve & streamline

### ISSUE THREAD

**Issue by shawnmgoulet** [capecodcommission/watershed-mvp#10]
Elapsed time for GETpointsFromPolygon for Pleasant Bay took 2:05, 3:11, 4:34 & 6:23, respectively with the Muni_ID filter and on an existing scnenario that had techs applied/deleted previously.

**1.**
 
![image](https://user-images.githubusercontent.com/3179974/61243866-df5c5480-a716-11e9-87e9-08fffd3f2f5c.png)

**2.** 

![image](https://user-images.githubusercontent.com/3179974/61244166-8ccf6800-a717-11e9-91c5-399048bd7114.png)

**3.**

![image](https://user-images.githubusercontent.com/3179974/61244538-7675dc00-a718-11e9-8dae-55b834ade572.png)

**4.** 

![image](https://user-images.githubusercontent.com/3179974/61297700-c0a79d80-a7aa-11e9-9355-e2e2789814a4.png)

**Comment by ghost** [comment]
**Time: 10:00am** Issue is intermittent.
**1:** [00m:18s, 00m:05s, 00m:05s, 00m:06s] Ran with Muni_id filter removed from getpoints stored proc
![image](https://user-images.githubusercontent.com/47121125/61298762-cd2cf580-a7ac-11e9-960b-87670446a6d1.png)

**2:** [00m:02s, 00m:03s, 00m: 02s, 00m:03s] Ran with parcels removed from parcelMaster for scenario
![image](https://user-images.githubusercontent.com/47121125/61299863-e6cf3c80-a7ae-11e9-8bc6-31617bfefb07.png)

**3:** [00m:03s, 00m:03s, 00m:03s, 00m:03s] Ran with new scenario
![image](https://user-images.githubusercontent.com/47121125/61300141-6c52ec80-a7af-11e9-9bcc-6428805eb0ee.png)

**4:** [00m:03s, 00m:03s, 00m:03s, 00m:03s] Ran with new scenario, Muni_id filter added back into getpoints stored proc
![image](https://user-images.githubusercontent.com/47121125/61300843-bd171500-a7b0-11e9-8443-6fa25320b57f.png)

**Comment by shawnmgoulet** [comment]
Currently taking +12 secs to run getPointsFromPolygon upon Fertilizer Management technology selection. Reopening.

**1.** 

![image](https://user-images.githubusercontent.com/3179974/61325982-df765600-a7e3-11e9-9237-a6b7e33e12aa.png)
