### ISSUE TITLE
In-Embayment: Accordion Header: Update css to mimic other treatment headers

### ISSUE THREAD

**Issue by ghost** [capecodcommission/watershed-mvp#43]
![image](https://user-images.githubusercontent.com/47121125/62316429-6de60b00-b465-11e9-80d6-9609e7c8cdf4.png)
![image](https://user-images.githubusercontent.com/47121125/62316448-7a6a6380-b465-11e9-9101-a91a541585cd.png)
![image](https://user-images.githubusercontent.com/47121125/62316471-85bd8f00-b465-11e9-98a5-72994f27a903.png)

**Comment by shawnmgoulet** [comment]
Closing as the accordion's layout is completely changing.
