### ISSUE TITLE
App: Add treatment strategy label to define duplicate treatments in treatment stack, scenario results, etc

### ISSUE THREAD

**Issue by ghost** [capecodcommission/watershed-mvp#44]
"For instance Wellfleet wants to add five different Aquacultures and after you add all five when the user is not  sure which one is which when they want to edit them."

**Comment by shawnmgoulet** [comment]
We've added the Treatment ID on hover of the Treatment Stack icon & the highlighting of the map graphic on hover of the Treatment Stack icon.
