### ISSUE TITLE
Fert/Storm Management: Bypass initial Treatment creation

### ISSUE THREAD

**Issue by ghost** [capecodcommission/watershed-mvp#81]
Modify tech/get API route to bypass Treatment creation for Fert/Storm Management, in order to add Treatment creation functionality to their respective tech/apply API route.

**Comment by mcarloni4** [comment]
Fertilizer Management blade is now independent of Treatment creation prior to loading the modal. Treatment creation and parcel association are now done on_apply.

Stormwater Management blade has several more treatment references that need to be resolved.

**Comment by ghost** [comment]
Fertilizer Management Treatment creation is now handled by the apply_percent API route.
Circling back later to finish Stormwater Management related issues.
