### ISSUE TITLE
Collect Move: Design blade layout

### ISSUE THREAD

**Issue by ghost** [capecodcommission/watershed-mvp#97]

**Comment by shawnmgoulet** [comment]
This layout replaces the former blade used by technologies:

`WHERE technology_id IN(603, 604, 605, 606, 607, 608)`
**SEPTIC TECHNOLOGIES**

- (2) Cluster Treatments
- Conventional Treatment
- Advanced Treatment
- Satellite Treatment
- Satellite Treatment - Enhanced

This blade partially replaces the former _Septic: Redesign blade layout_ issue #101.
